package com.lengjiye.toolkit.activity;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.lengjiye.toolkit.R;
import com.lengjiye.toolkit.view.StretchTextView;

public class StretchTextActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_stretch_text);

        StretchTextView view = (StretchTextView) findViewById(R.id.stretch);
        view.setContent("阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的阿萨德擦拭的成熟的擦实打实的");
    }
}
